name: remote_form
description: Manage form and UI from backend side as JSON
version: 0.0.3
homepage: https://github.com/jaumard/remote_ui/tree/master/packages/remote_form

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter_hooks: ">=0.10.0 <1.0.0"
  remote_ui: ">=0.0.9 <0.1.0"
    #path: '../remote_ui'
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
