name: remote_ip_camera
description: Camera IP addon for remote ui package, allow you to add a remote widget that show mjpeg stream from URL
version: 1.1.4
homepage: https://github.com/jaumard/remote_ui/tree/master/packages/remote_ip_camera

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter_mjpeg: ">=1.2.9 <1.3.0"
    #path: '../../../flutter_mjpeg'
  flutter_hooks: ">=0.10.0 <1.0.0"
  remote_ui: ">=0.0.9 <0.1.0"
    #path: '../remote_ui'
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
